import { createServer } from 'node:http'
import { randomBytes } from 'node:crypto'
import { getConnection } from '../database.js'

const port = Number(process.env.HR_PORT || 8082)
const newId = () => randomBytes(12).toString('hex')
const send = (res, status, data) => { res.writeHead(status, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Content-Type, X-User-Id, X-User-Role', 'Access-Control-Allow-Methods': 'GET, POST, PUT, PATCH, OPTIONS' }); res.end(JSON.stringify(data)) }
async function body(req) { let text = ''; for await (const chunk of req) text += chunk; try { return JSON.parse(text || '{}') } catch { return null } }
async function run(sql, binds = {}, options = {}) { const conn = await getConnection(); try { return await conn.execute(sql, binds, options) } finally { await conn.close() } }
const admin = (req, res) => req.headers['x-user-role'] === 'HR' ? true : (send(res, 403, { message: 'HR access required.' }), false)

async function profile(req, res, url) {
  const userId = url.searchParams.get('userId') || req.headers['x-user-id']; if (!userId) return send(res, 400, { message: 'userId is required.' })
  if (req.method === 'GET') { const rows = (await run(`SELECT u.id,u.full_name,u.employee_id,u.email,u.role,p.phone,p.address,p.department,p.designation,p.joining_date,p.profile_picture FROM users u LEFT JOIN employee_profiles p ON p.user_id=u.id WHERE u.id=:userId`, { userId })).rows; return rows[0] ? send(res, 200, rows[0]) : send(res, 404, { message: 'Profile not found.' }) }
  const data = await body(req); const hr = req.headers['x-user-role'] === 'HR'; const sql = hr ? 'UPDATE employee_profiles SET phone=:phone,address=:address,department=:department,designation=:designation,profile_picture=:picture WHERE user_id=:userId' : 'UPDATE employee_profiles SET phone=:phone,address=:address,profile_picture=:picture WHERE user_id=:userId'; await run(sql, { userId, phone: data.phone || null, address: data.address || null, department: data.department || null, designation: data.designation || null, picture: data.profilePicture || null }, { autoCommit: true }); return send(res, 200, { message: 'Profile updated.' })
}
async function attendance(req, res, url) {
  const userId = url.searchParams.get('userId') || req.headers['x-user-id']; const all = url.searchParams.get('all') === 'true'; if (all && !admin(req, res)) return
  if (req.method === 'GET') { const where = all ? '' : 'WHERE a.user_id=:userId'; const rows = (await run(`SELECT a.id,u.full_name,u.employee_id,TO_CHAR(a.attendance_date,'YYYY-MM-DD') AS attendance_date,a.status,a.check_in,a.check_out FROM attendance a JOIN users u ON u.id=a.user_id ${where} ORDER BY a.attendance_date DESC`, all ? {} : { userId })).rows; return send(res, 200, rows) }
  const action = url.pathname.endsWith('check-in') ? 'check-in' : 'check-out'; const date = new Date().toISOString().slice(0, 10); const time = new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }); if (action === 'check-in') { try { await run("INSERT INTO attendance(id,user_id,attendance_date,status,check_in) VALUES(:id,:userId,TO_DATE(:dateText,'YYYY-MM-DD'),'Present',:time)", { id: newId(), userId, dateText: date, time }, { autoCommit: true }) } catch (error) { if (error.errorNum === 1) return send(res, 409, { message: 'Already checked in today.' }); throw error } } else await run("UPDATE attendance SET check_out=:time WHERE user_id=:userId AND attendance_date=TO_DATE(:dateText,'YYYY-MM-DD')", { userId, dateText: date, time }, { autoCommit: true }); return send(res, 200, { message: `${action} successful.` })
}
async function leaves(req, res, url) {
  const userId = url.searchParams.get('userId') || req.headers['x-user-id']; const all = url.searchParams.get('all') === 'true'; if (all && !admin(req, res)) return
  if (req.method === 'GET') { const where = all ? '' : 'WHERE l.user_id=:userId'; const rows = (await run(`SELECT l.id,u.full_name,u.employee_id,l.leave_type,TO_CHAR(l.from_date,'YYYY-MM-DD') AS from_date,TO_CHAR(l.to_date,'YYYY-MM-DD') AS to_date,l.remarks,l.status,l.hr_comment FROM leave_requests l JOIN users u ON u.id=l.user_id ${where} ORDER BY l.created_at DESC`, all ? {} : { userId })).rows; return send(res, 200, rows) }
  const data = await body(req); if (!data?.leaveType || !data?.fromDate || !data?.toDate || !data?.remarks) return send(res, 400, { message: 'Leave type, dates, and remarks are required.' }); await run("INSERT INTO leave_requests(id,user_id,leave_type,from_date,to_date,remarks,status) VALUES(:id,:userId,:type,TO_DATE(:fromDate,'YYYY-MM-DD'),TO_DATE(:toDate,'YYYY-MM-DD'),:remarks,'Pending')", { id: newId(), userId, type: data.leaveType, fromDate: data.fromDate, toDate: data.toDate, remarks: data.remarks }, { autoCommit: true }); return send(res, 201, { message: 'Leave request submitted.' })
}
async function review(req, res, leaveId) { if (!admin(req, res)) return; const data = await body(req); if (!['Approved', 'Rejected'].includes(data?.status)) return send(res, 400, { message: 'Use Approved or Rejected.' }); await run('UPDATE leave_requests SET status=:status,hr_comment=:hrComment,reviewed_by=:reviewedBy WHERE id=:leaveId', { status: data.status, hrComment: data.comment || null, reviewedBy: req.headers['x-user-id'], leaveId }, { autoCommit: true }); return send(res, 200, { message: `Leave ${data.status.toLowerCase()}.` }) }
async function payroll(req, res, url) { const all = url.searchParams.get('all') === 'true'; if (all && !admin(req, res)) return; const userId = url.searchParams.get('userId') || req.headers['x-user-id']; if (req.method === 'GET') { const where = all ? '' : 'WHERE p.user_id=:userId'; const rows = (await run(`SELECT p.id,u.full_name,u.employee_id,p.payroll_month,p.basic_salary,p.hra,p.other_allowance,p.deductions,(p.basic_salary+p.hra+p.other_allowance-p.deductions) AS net_salary,p.status FROM payroll p JOIN users u ON u.id=p.user_id ${where}`, all ? {} : { userId })).rows; return send(res, 200, rows) } if (!admin(req, res)) return; const data = await body(req); const targetId = url.pathname.split('/').pop(); const binds = { id: newId(), userId: targetId, month: data.payrollMonth, basic: Number(data.basicSalary || 0), hra: Number(data.hra || 0), other: Number(data.otherAllowance || 0), deductions: Number(data.deductions || 0), status: data.status || 'Draft' }; const exists = (await run('SELECT id FROM payroll WHERE user_id=:userId AND payroll_month=:month', { userId: targetId, month: data.payrollMonth })).rows[0]; await run(exists ? 'UPDATE payroll SET basic_salary=:basic,hra=:hra,other_allowance=:other,deductions=:deductions,status=:status WHERE user_id=:userId AND payroll_month=:month' : 'INSERT INTO payroll(id,user_id,payroll_month,basic_salary,hra,other_allowance,deductions,status) VALUES(:id,:userId,:month,:basic,:hra,:other,:deductions,:status)', binds, { autoCommit: true }); return send(res, 200, { message: 'Payroll saved.' }) }
async function dashboard(req, res) { if (!admin(req, res)) return; const [employees, present, pending] = await Promise.all([run("SELECT COUNT(*) AS total FROM users WHERE role = 'Employee'"), run("SELECT COUNT(*) AS total FROM attendance WHERE attendance_date = TRUNC(SYSDATE) AND status = 'Present'"), run("SELECT COUNT(*) AS total FROM leave_requests WHERE status = 'Pending'")]); return send(res, 200, { employees: employees.rows[0].TOTAL, present: present.rows[0].TOTAL, pendingLeaves: pending.rows[0].TOTAL }) }
async function employees(req, res) { if (!admin(req, res)) return; const rows = (await run("SELECT id, full_name, employee_id, email FROM users WHERE role = 'Employee' ORDER BY employee_id")).rows; return send(res, 200, rows) }

createServer(async (req, res) => { try { const url = new URL(req.url, `http://${req.headers.host}`); if (req.method === 'OPTIONS') return send(res, 204, {}); if (req.method === 'GET' && url.pathname === '/api/hr/health') return send(res, 200, { service: 'hr-service', status: 'ready' }); if (req.method === 'GET' && url.pathname === '/api/hr/dashboard') return dashboard(req, res); if (req.method === 'GET' && url.pathname === '/api/hr/employees') return employees(req, res); if (['GET', 'PUT'].includes(req.method) && url.pathname === '/api/hr/profile') return profile(req, res, url); if ((req.method === 'GET' && url.pathname === '/api/hr/attendance') || (req.method === 'POST' && url.pathname.startsWith('/api/hr/attendance/'))) return attendance(req, res, url); if (['GET', 'POST'].includes(req.method) && url.pathname === '/api/hr/leaves') return leaves(req, res, url); if (req.method === 'PATCH' && url.pathname.startsWith('/api/hr/leaves/')) return review(req, res, url.pathname.split('/').pop()); if ((req.method === 'GET' && url.pathname === '/api/hr/payroll') || (req.method === 'PUT' && url.pathname.startsWith('/api/hr/payroll/'))) return payroll(req, res, url); return send(res, 404, { message: 'Route not found.' }) } catch (error) { console.error(error); return send(res, 500, { message: 'HR service error.' }) } }).listen(port, () => console.log(`HR service running at http://localhost:${port}`))
