import { useState } from 'react'
import { CalendarCheck, CheckCircle2, CircleDollarSign, Clock3, Search, Users } from 'lucide-react'
import './HrPortal.css'

const staff = [{ name: 'Navaneetham', id: 'EMP-001', role: 'Software Developer', status: 'Present' }, { name: 'Priya Sharma', id: 'EMP-102', role: 'HR Executive', status: 'Present' }, { name: 'Arun Kumar', id: 'EMP-118', role: 'UI Designer', status: 'Leave' }, { name: 'Meera Iyer', id: 'EMP-125', role: 'QA Engineer', status: 'Present' }]
const initial = [{ name: 'Priya Sharma', id: 'EMP-102', type: 'Sick Leave', dates: '25 Aug 2026' }, { name: 'Arun Kumar', id: 'EMP-118', type: 'Paid Leave', dates: '28–29 Aug 2026' }, { name: 'Meera Iyer', id: 'EMP-125', type: 'Unpaid Leave', dates: '01 Sep 2026' }]
const Status = ({ value }) => <span className={`status ${value.toLowerCase().replace(' ', '')}`}>{value}</span>
const Card = ({ title, children }) => <article className="card">{title && <h2>{title}</h2>}{children}</article>
const Table = ({ heads, rows }) => <div className="table"><table><thead><tr>{heads.map(x => <th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i}>{r.map((x, j) => <td key={j}>{x}</td>)}</tr>)}</tbody></table></div>
export default function HrPortal({ page }) { const [pending, setPending] = useState(initial); const [notice, setNotice] = useState(''); let output = page === 'employees' ? <Employees /> : page === 'attendance' ? <Attendance /> : page === 'approvals' ? <Approvals pending={pending} setPending={setPending} notice={setNotice} /> : page === 'payroll' ? <Payroll notice={setNotice} /> : <Home />; return <>{notice && <div className="notice"><CheckCircle2 size={17} />{notice}</div>}{output}</> }
function Home() { return <><div className="hero"><div><small>DAYFLOW HRMS</small><h2>Team overview</h2><p>Manage your people and approvals from one place.</p></div></div><Stats /><div className="twocol"><Card title="Leave requests awaiting approval"><RequestList pending={initial} /></Card><Card title="Today’s attendance"><div className="ring"><b>87%</b><span>Present today</span><p>42 present · 3 on leave · 3 absent</p></div></Card></div></> }
function Employees() { const [selected, setSelected] = useState(null); const [saved, setSaved] = useState(''); return <><div className="actions"><div><small>PEOPLE</small><h2>Employee directory</h2></div><label className="search"><Search size={18} /><input placeholder="Search employees" /></label></div>{saved && <div className="notice"><CheckCircle2 size={17} />{saved}</div>}<Card><Table heads={['Employee', 'Employee ID', 'Role', 'Today', 'Action']} rows={staff.map(x => [<Person person={x} />, x.id, x.role, <Status value={x.status} />, <button className="edit-button" onClick={() => setSelected(x)}>Edit</button>])} /></Card>{selected && <Card title={`Edit ${selected.name}`}><form className="hr-edit-form" onSubmit={e => { e.preventDefault(); setSelected(null); setSaved('Employee details updated successfully.') }}><label>Full name<input defaultValue={selected.name} /></label><label>Employee ID<input defaultValue={selected.id} /></label><label>Email<input defaultValue={`${selected.name.toLowerCase().replace(' ', '.')}@dayflow.com`} /></label><label>Phone<input defaultValue="+91 98765 43210" /></label><label>Department<input defaultValue="Engineering" /></label><label>Designation<input defaultValue={selected.role} /></label><label>Basic salary<input defaultValue="35000" /></label><label>Address<input defaultValue="Chennai, Tamil Nadu" /></label><button>Save All Details</button></form></Card>}</> }
function Attendance() { const [view, setView] = useState('daily'); const weekly = ['Mon, 18 Aug', 'Tue, 19 Aug', 'Wed, 20 Aug', 'Thu, 21 Aug', 'Fri, 22 Aug']; return <><Stats /><div className="attendance-head"><p>HR can view attendance records for all employees.</p><div className="view-switch"><button className={view === 'daily' ? 'selected' : ''} onClick={() => setView('daily')}>Daily</button><button className={view === 'weekly' ? 'selected' : ''} onClick={() => setView('weekly')}>Weekly</button></div></div>{view === 'daily' ? <Card title="Today’s attendance"><Table heads={['Employee', 'Status', 'Check in', 'Check out']} rows={staff.map((x, i) => [x.name, <Status value={x.status} />, x.status === 'Leave' ? '—' : `09:0${4 + i} AM`, '—'])} /></Card> : <Card title="Weekly attendance — all employees"><Table heads={['Employee', ...weekly]} rows={staff.map((x, i) => [x.name, ...weekly.map((_, day) => <Status value={day === 2 && i === 2 ? 'Half-day' : day === 3 && i === 2 ? 'Leave' : day === 4 && i === 3 ? 'Absent' : 'Present'} />)])} /></Card>}</> }
function Approvals({ pending, setPending, notice }) { const [comments, setComments] = useState({}); const decide = (id, status) => { setPending(pending.filter(x => x.id !== id)); notice(`Leave request ${status.toLowerCase()} successfully. ${comments[id] ? 'Comment added to employee record.' : ''}`) }; return <Card title="Pending leave requests"><div className="requests">{pending.length ? pending.map(x => <div key={x.id} className="approval-request"><Person person={x} extra={`${x.type} · ${x.dates}`} /><textarea value={comments[x.id] || ''} onChange={e => setComments({ ...comments, [x.id]: e.target.value })} placeholder="Add approval comment for employee" /><section><button className="approve" onClick={() => decide(x.id, 'Approved')}>Approve</button><button className="reject" onClick={() => decide(x.id, 'Rejected')}>Reject</button></section></div>) : <p className="empty">All caught up! No leave requests waiting for approval.</p>}</div></Card> }
function Payroll({ notice }) { const [selected, setSelected] = useState(null); const [verified, setVerified] = useState(false); return <><div className="actions"><div><small>PAYROLL</small><h2>August 2026 payroll</h2></div><button onClick={() => notice('Payroll run created. Review salary details before publishing.')}>Run payroll</button></div><div className="stats"><Stat icon={CircleDollarSign} text="Total payroll" value="₹ 18.6L" color="blue" /><Stat icon={Users} text="Employees processed" value="48 / 48" color="purple" /><Stat icon={CheckCircle2} text="Payroll status" value={verified ? 'Verified' : 'Draft'} color="green" /></div><Card title="Employee salary details"><Table heads={['Employee', 'Role', 'Gross salary', 'Net salary', 'Action']} rows={staff.map((x, i) => [x.name, x.role, `₹ ${55 - i * 3},000`, `₹ ${52 - i * 3},500`, <button className="edit-button" onClick={() => setSelected(x)}>Update salary</button>])} /></Card>{selected && <Card title={`Salary structure — ${selected.name}`}><form className="payroll-form" onSubmit={e => { e.preventDefault(); setSelected(null); notice('Salary structure updated. Payroll accuracy needs verification.') }}><label>Basic salary<input defaultValue="35000" type="number" /></label><label>House rent allowance<input defaultValue="10000" type="number" /></label><label>Other allowance<input defaultValue="5000" type="number" /></label><label>Deductions<input defaultValue="1500" type="number" /></label><button>Save Salary Structure</button></form></Card>}<div className="payroll-check"><div><CheckCircle2 /><p><b>Payroll accuracy check</b><small>Confirm salary structure, deductions, and net pay before payroll is published.</small></p></div><button onClick={() => { setVerified(true); notice('Payroll verified for accuracy and ready to publish.') }}>{verified ? 'Verified' : 'Verify Accuracy'}</button></div></> }
function Stats() { return <div className="stats"><Stat icon={Users} text="Total employees" value="48" color="blue" /><Stat icon={Clock3} text="Present today" value="42" color="green" /><Stat icon={CalendarCheck} text="Pending leaves" value="3" color="purple" /></div> }; function Stat({ icon: Icon, text, value, color }) { return <article><i className={color}><Icon size={21} /></i><div><p>{text}</p><h3>{value}</h3></div></article> }; function Person({ person, extra }) { return <div className="emp"><span>{person.name[0]}</span><p><b>{person.name}</b><small>{extra || person.id}</small></p></div> }; function RequestList({ pending }) { return <div className="mini">{pending.map(x => <p key={x.id}><span>{x.name[0]}</span><b>{x.name}<small>{x.type} · {x.dates}</small></b><Status value="Pending" /></p>)}</div> }
